### PR TITLE
Make extra permissions work, fix cache key calculation MODAT-47

### PR DESCRIPTION
**Pull request by adamdickmeiss**
The URLEncoder.encode usage is OK and results in what appears
to be correct expanded permissions for extra-permission. The
extra permissions caching, however, is disabled by this and should
be fixed.

### CODE REVIEW

**Comment by marcjohnson-kint** [comment]
Does the disabling of the cache mean the long delay that is usually experienced only some of the time, now happens on each request?

**Comment by hjiebsco** [comment]
Fixed the module permission expanding issue and restored the use of cache.

**Comment by julianladisch** [comment]
Can you rename cacheEntries to cacheEnabled (or some other more self-explanatory name)?

**Comment by adamdickmeiss** [comment]
Note that the caching is still sub optimal.. There should be two cache entries.. Not one.

The first (and existing one) should cache the result of getPermissionsForUser. So the key obviously depends on user and tenant.

The second is the call toexpandPermissions. It does NOT depend on the user. This is important. The cache entry for that one can have a long TTL, because it only depends on ModuleDescriptors enabled for the tenant. These rarely changes!!!

I think the code would also be clearer if it was a simple "intercept" of those calls. Since the former have a short TTL it makes the 2nd call being called at times where that is not necessary.

**Comment by julianladisch** [comment]
@Adam Should we merge and use the solution of this pull request, and work on the 2 cache solution afterwards, or should we wait until the 2 cache solution is implemented?

**Comment by julianladisch** [comment]
Adam answered on Slack that we can merge this fix and should work on a two cache solution afterwards.

**Comment by julianladisch** [comment]
Created https://issues.folio.org/browse/MODAT-49 "Two caches for permissionsForUser and expandPermissions".

**Comment by hjiebsco** [comment]
Got the nod from @skoczko, I will merge minimal code changes needed to fix this issue (https://github.com/folio-org/mod-authtoken/pull/56), so circ and patron tickets can be unblocked. Since we are going to refactor the cache in MODAT-49, this PR won't be needed then.

**Pull request closed without merging**
