### PR TITLE
change default connect timeout from 10ms to 10s

### PR DESCRIPTION
**Pull request by hjiebsco**
Noticed frequent Folio permission retrieval timeout in my AWS environment. It turns out the default 10ms is way below the original default value 60s. See http://vertx.io/docs/apidocs/io/vertx/core/net/ClientOptionsBase.html#DEFAULT_CONNECT_TIMEOUT. I modified the value from 10ms to 10s and do not see the timeout error again.

### CODE REVIEW

**Comment by hjiebsco** [comment]
BTW, notice the different time unit between options.setConnectTimeout(**ms**) and options.setIdleTimeout(**s**)

**Comment by julianladisch** [comment]
Looks good to me and may be merged. @kurtnordstrom ?

**Comment by shale99** [comment]
do we need a 10s timeout for a connection - maybe 5s? this should be really quick as its just the connect part

**Comment by julianladisch** [comment]
The 10s timeout is a default in case property `perm.lookup.timeout` has not been set:
https://github.com/folio-org/mod-authtoken/blob/0c73aad7e30e32c96bf4122452422164c8496009/src/main/java/org/folio/auth/authtoken_module/MainVerticle.java#L70

**Pull request merged**
